Initial commit
ZayetsA/Hello_world pull request #1
Opened 2021-04-07 09:35 UTC by ZayetsA

Added 4 new fragments: **ButtonsFragment, CheckFragment, InputsFragment, MainFragment**. Implemented a **graph** of navigation between fragments. **Navigation** between fragments has been also implemented. The transition between the three child fragments is carried out by pressing certain buttons on the main fragment located in the main activity.

2021-04-08 07:43 UTC, LordKered requested changes

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
> +        minSdkVersion 30
Читайте задачу. Мин сдк должен быть 26

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Для чего эта библиотека? Она где-то используется?

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
>      testImplementation 'junit:junit:4.+'
Разве в приложении используются тесты?

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.4'
Смотри что ты копипастишь, зачем дубировать зависимости?

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
> +    implementation "androidx.navigation:navigation-dynamic-features-fragment:$nav_version"
Наверное стоило бы почитать для чего эта зависимость, перед тем как копипастить

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
> +    androidTestImplementation "androidx.navigation:navigation-testing:$nav_version"
Опять тесты. Ты их используешь?

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
> +    implementation "androidx.navigation:navigation-compose:1.0.0-alpha09"
Наверное стоило бы почитать для чего эта зависимость, перед тем как копипастить

2021-04-08 07:43 UTC, LordKered commented on app/build.gradle
>          applicationId "com.example.hello_world"
Наименование packageID. Это уникальный ид твоего приложение. Нижних подчеркиваний в ид не должно быть. Делимтром в данной ситуации выступает точка

2021-04-08 07:43 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +        return inflater.inflate(R.layout.fragment_buttons, container, false)
Задача была использовать ViewBinding.

2021-04-08 07:43 UTC, LordKered commented on app/src/main/java/com/example/hello_world/CheckFragment.kt
> +        return inflater.inflate(R.layout.fragment_check, container, false)
Та же самая ошибка что и во ButtonsFragment.onCreateView

2021-04-08 07:43 UTC, LordKered commented on app/src/main/java/com/example/hello_world/InputsFragment.kt
> +        return inflater.inflate(R.layout.fragment_inputs, container, false)
Та же самая ошибка что и во ButtonsFragment.onCreateView

2021-04-08 07:43 UTC, LordKered commented on app/src/main/java/com/example/hello_world/MainActivity.kt
>          setContentView(R.layout.activity_main)
Та же самая ошибка что и во ButtonsFragment.onCreateView

2021-04-08 07:43 UTC, LordKered commented on app/src/main/java/com/example/hello_world/MainActivity.kt
> +        navController = navHostFragment.findNavController()
У активити есть extension findNavController стоит использовать его

2021-04-08 07:43 UTC, LordKered commented on app/src/main/java/com/example/hello_world/MainFragment.kt
> +        when (v!!.id) {
если View - опициональное. То стоит обработать этот случай в ином случае если придет null то у тебя произойдет креш.

2021-04-08 08:07 UTC, VladimirOnix reviewed
Испраь ошибки на которые указал Евгений

2021-04-08 19:13 UTC, LordKered requested changes

2021-04-08 19:13 UTC, LordKered commented on app/src/main/java/com/example/hello_world/MainFragment.kt
> +        (activity as AppCompatActivity?)!!.supportActionBar!!.hide()
Уже лучше. Но. То что ты сделал...
Ты ожидаешь что активити если есть то оно будет или AppCompatActivity или null. Потом ты игнорируешь о том что у этого объекта опциональное состояние "!!" и говоришь, дай мне supportActionBar (который тоже между прочим опциональный и у него так же ты игнорируешь состояние), и спрячь.
Реальный случай:
1. Твое активити умерло в этот момент, и сюда пришел null - приложение крешнулось
2. Кто-то до этого место занулил actionBar - сюда пришло активити, но туллбара нет... приложение сново крешнулось.
Исправляй. Аналогично строчка ниже

2021-04-08 19:13 UTC, LordKered commented on app/src/main/java/com/example/hello_world/adapter/ButtonsAdapter.kt
> +class ButtonsAdapter(private val mButtons: List<ButtonModel>) :
Тут все очень плохо. 
1. mButtons - нейминг, джавы. Мы не ставим префикс m в котлине (member class)
2. Наименование buttons - звучит странно, то есть тут будут кнопочки? Кнопочки - вьюшки?
ViewHolder
1. Найменование. Должно содержать контекст текущего холдера
2. Месторасположение - должно находится вне адаптера, дабы инкапсулировать логику и позволить другим адаптерам так же использовать твой ViewHolder в своих целях
3. Должен работать с ViewBinding
4. У ViewHolder должен быть метод bind, который принимает модель которая относится к нему и дальше твоя логика. Этот метод нужно вызывать в Адаптере в методе onBindViewHolder. Твой адаптер не должен знать содержимое вьюхолдера, а вьюхолдер не должен знать содержимое адаптера.

2021-04-08 19:13 UTC, LordKered commented on app/src/main/java/com/example/hello_world/model/ButtonModel.kt
> +class ButtonModel(val name: String) {
Ужасная модель. Слишком много статики. Их не должно быть. Модель должна существовать только один раз в том месте где она используеться. То есть когда твой фрагмент умрет, модель так же должна умереть с ним =)

2021-04-08 19:13 UTC, LordKered commented on app/src/main/java/com/example/hello_world/model/ButtonModel.kt
> +            val input = "ноль раз два три четыре пять шесть семь восемь девять десять"
Хм... Я ужасный заказчик. Я хочу 100 кнопок как минимум... Ты будешь описывать такой список? Очень плохо.
Подумай (погугли, возможно иноформацию проще найти с английскими словами) какая закономерность в словах.

2021-04-08 19:13 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +        vButtons.layoutManager = LinearLayoutManager(this.context)
this точно нужен?

2021-04-08 19:13 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +        val vButtons = binding.rvButtons
Для чего выделять переменной дополнительные ресурсы, если ты и так на прямую обращаешься к ней?

2021-04-08 22:06 UTC, ZayetsA commented on app/src/main/java/com/example/hello_world/model/ButtonModel.kt
> +            val input = "ноль раз два три четыре пять шесть семь восемь девять десять"
`implementation group: 'com.ibm.icu', name: 'icu4j', version: '51.1'` пойдёт? Работает вроде хорошо, да и велосипед изобретать не хочется)

2021-04-09 13:26 UTC, TAEKsCode requested changes

2021-04-09 13:26 UTC, TAEKsCode commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +    private var _binding: FragmentButtonsBinding? = null
Зачем делать нулловый биндинг? Можно было точно так же как и с адаптером, сделать его lateinit:
private lateinit var binding: FragmentButtonsBinding, а потом его тупо инициализировать

2021-04-09 13:26 UTC, TAEKsCode commented on app/src/main/java/com/example/hello_world/MainFragment.kt
> +        navigationController = Navigation.findNavController(view)
Navigation можно не писать

2021-04-09 13:26 UTC, TAEKsCode commented on app/src/main/res/layout/activity_main.xml
>          app:layout_constraintLeft_toLeftOf="parent"
start to start, а то студия будет писать типа не пиши left, пиши start

2021-04-09 13:26 UTC, TAEKsCode commented on app/src/main/res/layout/fragment_buttons.xml
> +        android:layout_marginBottom="24dp"
Размеры можно в dimens вынести(Alt+Enter)

2021-04-09 14:24 UTC, ZayetsA commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +    private var _binding: FragmentButtonsBinding? = null
Делал по доках. Подскажите, есть ли существенная разница между `lateinit` и `null` оглавлением ?

2021-04-10 05:19 UTC, LordKered commented on app/src/main/java/com/example/hello_world/model/ButtonModel.kt
> +            val input = "ноль раз два три четыре пять шесть семь восемь девять десять"
Если библиотека выполняет текущую задачу и поддерживается на всех версиях которые поддерживает твое приложение (это с мин 26) в таком случае никаких проблем.

2021-04-10 05:36 UTC, LordKered commented on app/build.gradle
> +    implementation group: 'com.ibm.icu', name: 'icu4j', version: '51.1'
Тут надо немного подумать) Имплементация не для гредла.
Если не ошибаюсь тебе нужно переписать на implementation "com.ibm.icu:icu4j:51.1"

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +    private var _binding: FragmentButtonsBinding? = null
Да есть. lateinit - грубо говоря инизиализация будет сделана потом и если поле не опциональное - то нулл значения тут не будет.
Чем плох lateinit - если ты до инициализации попробуешь ее где-то использовать, то будет креш

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/InputsFragment.kt
> +            try {
Зачем тут try-catch?

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/InputsFragment.kt
> +            activity.currentFocus!!.windowToken, 0
Опять же, старайся вообще не использовать "!!". Потом будешь страдать из-за этого)
Исправь на корректный вид, с обраброткой нулла

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +        val local = Locale(language, Country)
Хороший момент, чтобы сделать внедрить правильную локализацию)
Locale - стоит использовать текущею (та которая сейчас установлена на телефоне)
Ресурсы (res) по умолчанию - всегда English, рядом стоит создать ресурсы для русской локализации

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +    private fun convertIntoWords(str: Double, language: String, Country: String): String {
Переменные не должны начинаться с большой буквы. Тут правило camelCase

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +                "кнопка номер " + convertIntoWords(
"кнопка номер" - стоит вынести в ресурсы. Никаких хадкодных строк)

2021-04-10 05:36 UTC, LordKered commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +                    "rus",
В идеале ты это удалишь, но на будущее. Если создаешь такого вида строки, будь добр выносить их в константы с правильным неймингом.

2021-04-10 06:23 UTC, ZayetsA commented on app/src/main/java/com/example/hello_world/InputsFragment.kt
> +            try {
по старинке обработал NullPointExeption, который вылезал, когда кнопка нажималась с закрытой клавиатурой

2021-04-10 06:26 UTC, ZayetsA commented on app/src/main/java/com/example/hello_world/ButtonsFragment.kt
> +    private var _binding: FragmentButtonsBinding? = null
и всё же, как правильнее ?)

2021-04-11 12:31 UTC, TAEKsCode approved these changes

2021-04-11 12:31 UTC, TAEKsCode commented on app/src/main/java/com/example/hello_world/MainFragment.kt
> +                binding.openButtons.id -> navigationController?.navigate(R.id.action_mainFragment_to_buttonsFragment)
Если не выносить нав контроллер в отдельную переменную, а делать просто findNavController(), то можно избавиться от пары строчек кода и от записей по типу этой navigationController?.navigate

2021-04-11 12:31 UTC, TAEKsCode commented on app/src/main/res/drawable/custom_cb.xml
> +    <item android:drawable="@drawable/checkbox_on_bg" android:state_checked="true" />
Нейминг. Каждый ресурс нужно привязывать к контексту, тут checkbox_on_bg и допустим это шарик, а если во втором фрагменте понадобится такой же checkbox_on_bg, только квадрат, что тогда?

2021-04-11 12:31 UTC, TAEKsCode commented on app/src/main/res/layout/fragment_buttons.xml
> +        app:backgroundTint="#D5D5D5"
android:backgroundTint="#D5D5D5"
app:backgroundTint="#D5D5D5"
В чём разница?
Ещё, android:focusable="true", android:clickable="true" это точно нужно?

2021-04-11 12:31 UTC, TAEKsCode commented on app/src/main/res/layout/fragment_inputs.xml
> +    android:padding="20dp"
Dimen

2021-04-12 06:04 UTC, LordKered requested changes

2021-04-12 10:01 UTC, LordKered approved these changes

2021-04-12 10:03 UTC, VladimirOnix approved these changes

2021-04-12 10:16 UTC, onix-roman approved these changes

2021-04-12 10:17 UTC, merged